# Generated by Django 4.2.7 on 2023-12-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='Descricao',
            field=models.CharField(max_length=200),
        ),
    ]
