# Generated by Django 4.2.7 on 2023-12-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='img',
            field=models.CharField(default='#', max_length=50),
        ),
    ]
