# Generated by Django 4.2.7 on 2023-12-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='img',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
