# Generated by Django 4.2.7 on 2023-12-04 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categorias_descricao'),
        ('produtos', '0003_alter_produto_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='Categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='categorias.categorias'),
        ),
    ]
