# Generated by Django 4.2.7 on 2023-11-30 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20)),
                ('Descricao', models.CharField(max_length=20)),
                ('Loja', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='loja.loja')),
            ],
        ),
    ]
